title: ByteChef
description: Cybersecurity | AI/ML Security | Penetration Testing
url: "https://the-byte-chef.github.io"
author: ByteChef
email: ""

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  writeups:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
